name: hadith_apps
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.2
  get: ^4.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:


  uses-material-design: true


  assets:
    - assets/images/


  # example:
  fonts:
    - family: kalpurush
      fonts:
        - asset: fonts/kalpurush/kalpurush.ttf
#        - asset: fonts/Schyler-Italic.ttf
#          style: italic
    - family: kfgq
      fonts:
        - asset: fonts/kfgq/font_kfgq.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
